---
- name: Install Loki
  hosts: grafana,grafanaTestingVM
  become: yes
  vars_files: ./vars.yml

  tasks:
  - name: Install unzip for unpacking archives 
    apt:
      name: unzip
      state: present
    become: true

  - name: Install loki using wget and unzip it
    shell:
      chdir: "{{home_dir}}"
      cmd: |
        wget https://github.com/grafana/loki/releases/download/{{loki_version}}/loki-linux-amd64.zip
        unzip "loki-linux-amd64.zip"  
        chmod a+x "loki-linux-amd64"
        sudo mv ./loki-linux-amd64 /usr/local/bin/loki

  - name: Install default loki configuration yaml
    copy:
      src: ./resources/loki-local-config.yaml
      dest: /etc/loki-local-config.yaml

  - name: Copy loki.service (unit for systemd) to /etc/systemd/system folder
    copy:
      src: ./resources/loki.service
      dest: /etc/systemd/system
    become: true

  - name: Load loki unit and start it
    systemd:
      name: loki
      state: started
      daemon_reload: true
      enabled: true 
    become: true
