global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates: 
- '/etc/prometheus/alertmanager_templates/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
# A default receiver
  receiver: mailNotify
  routes:
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: #team-X-mails
    routes:
    - match:
        severity: critical
      receiver: mailNotify
  - match:
      service: files
    receiver: mailNotify

    
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']

receivers:
- name: mailNotify
  email_configs:
  - to: 'aslikeme@mail.ru'
    from: 'cl4ssique@yandex.ru'
    smarthost: 'smtp.yandex.ru:465'
    auth_username: 'cl4ssique@yandex.ru'
    auth_identity: 'cl4ssique@yandex.ru'
    auth_password: 'fffebaanztlxecyz'
    send_resolved: true
    require_tls: false

