---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: cadvisor-on-rocky
    image: eniocarboni/docker-rockylinux-systemd:9
    image_version: latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    groups:
      - extra_options
    volumes:
      # cadvisor needs the cgroup mount to access metrics
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu
  - name: cadvisor-on-ubuntu-20-04
    image: eniocarboni/docker-ubuntu-systemd:20.04
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    groups:
      - extra_options
    volumes:
      # cadvisor needs the cgroup mount to access metrics
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu

lint: |
  yamllint .
  ansible-lint
  flake8

provisioner:
  namefs/fs/cgroupcgroup: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
