---
serviceName: "alertmanager"
userId: "alertmanager"
groupId: "alertmanager"
exec_command: "/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/data/alertmanager"
version: "0.28.1"
alertmanager_domain: "monitoring.skbx-domain.ru"